# -*- coding: utf-8 -*-
"""20250108tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNNz7FGheeQHYxr9N_OqFEHJ65wzapCh
"""

!pip install --upgrade git+https://github.com/mschongchulshin/fatigue_life_predictor.git

import pandas as pd
from fatigue_life_predictor.model import load_trained_model, load_scalers, predict_fatigue_life
from google.colab import files
import io

# File upload
print("Upload the Excel file to be used for prediction.")
uploaded = files.upload()
for file_name in uploaded.keys():
    df = pd.read_excel(io.BytesIO(uploaded[file_name]))

# Load model and scalers
model = load_trained_model()
scaler, nf_scaler = load_scalers()

# Perform prediction
predicted_fatigue_life = predict_fatigue_life(model, scaler, nf_scaler, df)
print("Predicted fatigue life:", predicted_fatigue_life)